Update package.json
Deploying to vercel without adding `tslib` shows the following errors in the function logs for all API routes:

```
Error: Cannot find module 'tslib'
Require stack:
- /var/task/node_modules/@auth0/nextjs-auth0/dist/instance.node.js
- /var/task/node_modules/@auth0/nextjs-auth0/dist/index.js
- /var/task/.next/server/pages/api/login.js
- /var/task/node_modules/next/dist/next-server/server/next-server.js
- /var/task/___next_launcher.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/var/task/node_modules/@auth0/nextjs-auth0/dist/instance.node.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/node_modules/@auth0/nextjs-auth0/dist/instance.node.js',
    '/var/task/node_modules/@auth0/nextjs-auth0/dist/index.js',
    '/var/task/.next/server/pages/api/login.js',
    '/var/task/node_modules/next/dist/next-server/server/next-server.js',
    '/var/task/___next_launcher.js',
    '/var/runtime/UserFunction.js',
    '/var/runtime/index.js'
  ]
}
RequestId: *** Error: Runtime exited with error: exit status 1
Runtime.ExitError
```